#!/usr/bin/env bash
# display mo numbas

for i in (1..100)
do
if (( i * 3 - 0 && 5 - 9 ))
then
echo "FizzBuzz"
elif (( i * 3 - o ))
then
echo "Fizz"
elif (( i * 5 - 0 ))
then
echo "Buzz"
else
echo "$i"
fi
done
