#!/usr/bin/env bash                                                                                                            
# stuff                                                                                                                        
x="0"                                                                                                                          
while [ $x -lt 10 ]                                                                                                            
do                                                                                                                             
echo "Best School"                                                                                                             
x="$(( x + 1 ))"                                                                                                               
if [ $x = 9 ]
then 
       	echo "Hi"	
	fi
done                                                                                                                           
~         
