#!/usr/bin/env bash                                                                                                            
# stuff                                                                                                                        
x="0"                                                                                                                          
while [ $x -lt 10 ]                                                                                                            
do
if [ $count -eq 9 ]
then
echo "Hi"
fi
echo "Best School"
((x++))
done       
