#!/usr/bin/env bash
# displays numbers

x=1

while [ $x -le 20 ]
do
echo "$count"
case $count in
	"4") echo "bad luck from China";;
	"9") echo "bad luck from Japan";;
	"17") echo "bad luck from Italy";;
esac
	((x++))
done
