#!/usr/bin/env bash 
# bash give info

if [ -e "school" ]
then
echo "school file exists"
if [ -g "school" ]
then
echo "school file is empty"
fi
if [ -f "school" ]
then
echo "school is a regular file"
fi
else
echo "school file does not exist"
fi
