#!/usr/bin/env bash
# complicated

if [ "${1}" == "start" ]
then
	./manage_my_process &
	touch /var/run/my_process.pid
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "${!}" == "stop" ]
then
	echo "manage_my_process stopped"
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
elif [ "${1}" == "restart" ]
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	./manage_my_process.pid &
	touch /var/run/my_process.pid
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
